### ISSUE TITLE
bug en nav 

### ISSUE THREAD

**Issue by Betaris** [maufuenbus/electroriders#15]
cuando la pestaña es grande se ven los marcos de cada item del menu,  a esto hay que
- arreglar margenes, tamaño o padding.

cuando la ventana es responsiva el item "marco" del menu se esconde, 
- cuando se agranda la pantalla con el menu desplegado el item marco "sigue sin aparecer"
- agregar funcionalidad que si se apreta fuera del menu responsivo, este se cierre automaticamente.

**Comment by maufuenbus** [comment]
Solucionado
